[package]
name = "easytshark"
version = "1.0.2"
description = "EasyTshark"
authors = ["you"]
edition = "2021"

[lib]
name = "easytshark_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools", "macos-private-api"] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
tauri-plugin-log = "2"
tauri-plugin-os = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
futures-util = "0.3"
once_cell = "1.19"
md5 = "0.7"
chrono = "0.4"
num_cpus = "1.16"
sys-info = "0.9"
log = "0.4"
